### ISSUE TITLE
Import error of PiRGBArray using latest Raspbian OS Jan 2022

### ISSUE THREAD

**Issue by Clark1216** [armindocachada/raspberrypi-docker-tensorflow-opencv#4]
I encountered Import error of PiRGBArray after using latest Raspbian OS Jan 2022

OS version is the only thing I changed, but I understand is not sensible. Anyone has solutions?

Traceback (most recent call last):
  File "example.py", line 2, in <module>
    from picamera.array import PiRGBArray
  File "/usr/local/lib/python3.7/dist-packages/picamera/__init__.py", line 72, in <module>
    from picamera.exc import (
  File "/usr/local/lib/python3.7/dist-packages/picamera/exc.py", line 41, in <module>
    import picamera.mmal as mmal
  File "/usr/local/lib/python3.7/dist-packages/picamera/mmal.py", line 47, in <module>
    from .bcm_host import VCOS_UNSIGNED
  File "/usr/local/lib/python3.7/dist-packages/picamera/bcm_host.py", line 47, in <module>
    _lib = ct.CDLL('libbcm_host.so')
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbcm_host.so: cannot open shared object file: No such file or directory

**Comment by Clark1216** [comment]
New Debian OS 11 no longer supports picamera libraries. Better to use legacy Debian OS 10 to run the code
